version: "3.9"
services:
    api:
        build: 
            context: .
            dockerfile: AireBugTrackerApi/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
           - "8010:1433"
        environment:
           SA_PASSWORD: "Dev_Password123"
           ACCEPT_EULA: "Y"